/**
 * Standard application error codes used in the error response envelope.
 * Maps to the FRD "Standard Response Format" error shape.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMIT = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  PASSWORD_POLICY = 'PASSWORD_POLICY_VIOLATION',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SESSION_REVOKED = 'SESSION_REVOKED',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  AI_NOT_ENABLED = 'AI_NOT_ENABLED',
}
