/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as StudentRouteImport } from './routes/student'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as StudentOpportunitiesRouteImport } from './routes/student.opportunities'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentRoadmapRouteImport } from './routes/student.roadmap'
import { Route as StudentSkillsRouteImport } from './routes/student.skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentOpportunitiesRoute = StudentOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRoadmapRoute = StudentRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSkillsRoute = StudentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/platform': typeof PlatformRoute
  '/stories': typeof StoriesRoute
  '/student': typeof StudentRouteWithChildren
  '/workspaces': typeof WorkspacesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/skills': typeof StudentSkillsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/platform': typeof PlatformRoute
  '/stories': typeof StoriesRoute
  '/workspaces': typeof WorkspacesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/skills': typeof StudentSkillsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/platform': typeof PlatformRoute
  '/stories': typeof StoriesRoute
  '/student': typeof StudentRouteWithChildren
  '/workspaces': typeof WorkspacesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/opportunities': typeof StudentOpportunitiesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/roadmap': typeof StudentRoadmapRoute
  '/student/skills': typeof StudentSkillsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/platform'
    | '/stories'
    | '/student'
    | '/workspaces'
    | '/admin/analytics'
    | '/admin/students'
    | '/student/applications'
    | '/student/opportunities'
    | '/student/profile'
    | '/student/roadmap'
    | '/student/skills'
    | '/admin/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/platform'
    | '/stories'
    | '/workspaces'
    | '/admin/analytics'
    | '/admin/students'
    | '/student/applications'
    | '/student/opportunities'
    | '/student/profile'
    | '/student/roadmap'
    | '/student/skills'
    | '/admin'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/platform'
    | '/stories'
    | '/student'
    | '/workspaces'
    | '/admin/analytics'
    | '/admin/students'
    | '/student/applications'
    | '/student/opportunities'
    | '/student/profile'
    | '/student/roadmap'
    | '/student/skills'
    | '/admin/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  PlatformRoute: typeof PlatformRoute
  StoriesRoute: typeof StoriesRoute
  StudentRoute: typeof StudentRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/opportunities': {
      id: '/student/opportunities'
      path: '/opportunities'
      fullPath: '/student/opportunities'
      preLoaderRoute: typeof StudentOpportunitiesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/roadmap': {
      id: '/student/roadmap'
      path: '/roadmap'
      fullPath: '/student/roadmap'
      preLoaderRoute: typeof StudentRoadmapRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/skills': {
      id: '/student/skills'
      path: '/skills'
      fullPath: '/student/skills'
      preLoaderRoute: typeof StudentSkillsRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentOpportunitiesRoute: typeof StudentOpportunitiesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRoadmapRoute: typeof StudentRoadmapRoute
  StudentSkillsRoute: typeof StudentSkillsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentOpportunitiesRoute: StudentOpportunitiesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRoadmapRoute: StudentRoadmapRoute,
  StudentSkillsRoute: StudentSkillsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  PlatformRoute: PlatformRoute,
  StoriesRoute: StoriesRoute,
  StudentRoute: StudentRouteWithChildren,
  WorkspacesRoute: WorkspacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
